// Libs
import { marked } from 'marked';
import DOMPurify from 'dompurify';
import parse from 'html-react-parser';

export const useMarkdownParser = (markdown) => {
	try {
		marked.use({ gfm: true, breaks: true });

		const parsedMarkdown = marked.parse(markdown);

		// sanitize the HTML content generated by the `marked` library.
		const result = DOMPurify.sanitize(parsedMarkdown);
		return parse(result);
	} catch (error) {
		console.error('Error parsing the given html: ', error);
	}
};
