// Libs
import { marked } from 'marked';
import DOMPurify from 'dompurify';
import parse from 'html-react-parser';

export const useParser = (text) => {
	try {
		const markedContent = marked.parse(text);

		// sanitize the HTML content generated by the `marked` library.
		const purifiedContent = DOMPurify.sanitize(markedContent);
		return parse(purifiedContent);
	} catch (error) {
		console.error('Error parsing the given html: ', error);
	}
};
